# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rutgers IEEE
tagline:          Student Branch
description:      
url:              
baseurl:          /

author:
  name:           
  url:            

paginate:         5

github:
  org:           https://github.com/rutgers
